PROJECT_NAME = "League Call"

DB_PROTOCOL = "postgresql"
DB_URL = "@format {this.DB_PROTOCOL}://{env[PG_USER]}:{env[PG_PASSWORD]}@{env[PG_HOST]}:{env[PG_PORT]}/{env[PG_DB_NAME]}"

LOL_REGION = "BR1"

PREFIX = "!"

ROLE_CONFIGURED_ID = 1025067188383666236
REGISTER_GAME_CHANNEL_ID = 1025603028927135794
OWNER_ID = 145243718364954624
